### ISSUE TITLE
screentoworld.inc: Invalid Instructions.

### ISSUE THREAD

**Issue by Crayder** [Shiska/pawn#2]
I had no clue what my problem was. Your version of my update caused one of my commands to always terminate and return 0. Using crashdetect I got this:

	[debug] Run time error 6: "Invalid instruction"
	[debug]  Unknown opcode 0x0 at address 0x00042F58
	[debug] AMX backtrace:
	[debug] #0 00042f58 in ScreenToWorld (playerid=0, Float:screenX=320.00000, Float:screenY=240.00000, &Float:vX=@000ae1a0 0.59121, &Float:vY=@000ae19c 0.67324, &Float:vZ=@000ae198 -0.44409) at BLAHBLAHBLAH
	
So it's something to do with the returned vectors of ScreenToWorld.

**Comment by Shiska** [comment]
Didn't expect that, thats a bug within the preprocessor which doesn't compile the functions within the #if checks although they are used in STW and WTS causing an Invalid instruction error
Removed these again and renamed the stock to prevent problems with other scripts
