### ISSUE TITLE
447 vs 448

### ISSUE THREAD

**Issue by Crayder** [Shiska/pawn#4]
I'm not sure how you determined 447 was the correct y for textdraws, but you were off by 1. According to main.scm (the entire gtasa script), the correct textdraw range is 448.0.

The following lines are all screen relative lines from different areas of main.scm.

	038E: draw_box_position 320.0 224.0 size 640.0 448.0 RGBA 0 0 0 255 
	038E: draw_box_position 320.0 224.0 size 640.0 448.0 RGBA 0 0 0 255 
	  $tempvar_Float_2 > 448.0 
	038E: draw_box_position 320.0 224.0 size 640.0 448.0 RGBA 0 0 0 255 
	  $tempvar_Float_2 > 448.0 
	85A5:   not is_area_center 668@(227@,10f) 678@(227@,10f) scale 8.0 8.0 overlaping_area_center 320.0 224.0 scale 640.0 448.0 
	85A5:   not is_area_center 688@ 689@ scale 16.0 16.0 overlaping_area_center 320.0 224.0 scale 640.0 448.0 
	038E: draw_box_position 320.0 224.0 size 640.0 448.0 RGBA 0 0 0 255 
	  $tempvar_Float_2 > 448.0 
	038E: draw_box_position 320.0 224.0 size 640.0 448.0 RGBA 0 0 0 255 
	038D: draw_texture 9 position 320.0 224.0 size 640.0 448.0 RGBA 150 150 150 255 
	038E: draw_box_position 320.0 224.0 size 640.0 448.0 RGBA 0 0 0 255

**Comment by Shiska** [comment]
Could be, just took a value I think was matching :)
